### ISSUE TITLE
Possible VRID collision?

### ISSUE THREAD

**Issue by mandre** [openshift/baremetal-runtimecfg#22]
Not sure this is really the case (haven't observed it), the use of a checksum algo to compute the VRID could lead to collision -- especially on a small pool of 255 possible values.

Would it be possible to add a check in the code to ensure the VRIDs are different?

**Comment by cybertron** [comment]
This is definitely a possibility, and it's even worse than just collisions between our three VIPs. It's possible a deployer could have keepalived running on their network already for other services and we might accidentally pick one of their existing VRIDs. Ideally we would check for ids already in use on the network when we select ours and have a consistent fallback mechanism to deal with collisions.

The check in the code should be pretty easy to write, but I'm not sure how looking for existing ids on the network would work. So far it hasn't been a big problem so we haven't prioritized solving it.

**Comment by mandre** [comment]
This has been fixed with #23 
/close
